# Generated by Django 4.1.4 on 2022-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
